const imageMap = {
    // Covid Curriculum
    "covid-1": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-1.jpg'),
    "covid-2": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-2.jpg'),
    "covid-3": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-3.jpg'),
    "covid-4": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-4.jpg'),
    "covid-5": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-5.jpg'),
    "covid-6": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-6.jpg'),
    "covid-7": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-7.jpg'),
    "covid-8": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-8.jpg'),
    "covid-9": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-9.jpg'),
    "covid-10": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-10.jpg'),
    "covid-11": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-11.jpg'),
    "covid-12": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-12.jpg'),
    "covid-13": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-13.jpg'),
    "covid-14": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-14.jpg'),
    "covid-15": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-15.jpg'),
    "covid-16": require('../assets/books/covid-resources/Covid Curriculum, For Kindle-16.jpg'),
  
    // Stepping Stones
    "step-1": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-1.jpg'),
    "step-2": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-2.jpg'),
    "step-3": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-3.jpg'),
    "step-4": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-4.jpg'),
    "step-5": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-5.jpg'),
    "step-6": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-6.jpg'),
    "step-7": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-7.jpg'),
    "step-8": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-8.jpg'),
    "step-9": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-9.jpg'),
    "step-10": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-10.jpg'),
    "step-11": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-11.jpg'),
    "step-12": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-12.jpg'),
    "step-13": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-13.jpg'),
    "step-14": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-14.jpg'),
    "step-15": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-15.jpg'),
    "step-16": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-16.jpg'),
    "step-17": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-17.jpg'),
    "step-18": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-18.jpg'),
    "step-19": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-19.jpg'),
    "step-20": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-20.jpg'),
    "step-21": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-21.jpg'),
    "step-22": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-22.jpg'),
    "step-23": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-23.jpg'),
    "step-24": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-24.jpg'),
    "step-25": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-25.jpg'),
    "step-26": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-26.jpg'),
    "step-27": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-27.jpg'),
    "step-28": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-28.jpg'),
    "step-29": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-29.jpg'),
    "step-30": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-30.jpg'),
    "step-31": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-31.jpg'),
    "step-32": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-32.jpg'),
    "step-33": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-33.jpg'),
    "step-34": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-34.jpg'),
    "step-35": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-35.jpg'),
    "step-36": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-36.jpg'),
    "step-37": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-37.jpg'),
    "step-38": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-38.jpg'),
    "step-39": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-39.jpg'),
    "step-40": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-40.jpg'),
    "step-41": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-41.jpg'),
    "step-42": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-42.jpg'),
    "step-43": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-43.jpg'),
    "step-44": require('../assets/books/stepping-stones/Final Stepping Stones Digital-part-44.jpg'),
  
    // Full Book Cover
    "step-full": require('../assets/books/stepping-stones/Full Stepping Stones Digital.jpg')
  };
  
  export default imageMap;
  